// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HotelApp.Model;

[Table("Guest")]
public partial class Guest
{
    [Key]
    [Column("Guest_No")]
    public int GuestNo { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Address { get; set; }

    [InverseProperty("GuestNoNavigation")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}