// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HotelApp.Model;

[Table("Hotel")]
public partial class Hotel
{
    [Key]
    [Column("Hotel_No")]
    public int HotelNo { get; set; }

    [Required]
    [StringLength(30)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Address { get; set; }

    [InverseProperty("HotelNoNavigation")]
    public virtual ICollection<Room> Rooms { get; set; } = new List<Room>();
}