// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HotelApp.Model;

[PrimaryKey("RoomNo", "HotelNo")]
[Table("Room")]
public partial class Room
{
    [Key]
    [Column("Room_No")]
    public int RoomNo { get; set; }

    [Key]
    [Column("Hotel_No")]
    public int HotelNo { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string Types { get; set; }

    public double? Price { get; set; }

    [InverseProperty("Room")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [ForeignKey("HotelNo")]
    [InverseProperty("Rooms")]
    public virtual Hotel HotelNoNavigation { get; set; }
}